# Generated by Django 5.2.7 on 2026-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdiary',
            name='poster_url',
            field=models.TextField(blank=True, verbose_name='Poster URL'),
        ),
    ]
