# Generated by Django 5.2.7 on 2026-04-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactsobranch',
            name='assigned_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_branches', to='api.district'),
        ),
        migrations.AddField(
            model_name='tactsobranch',
            name='overseer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_universities', to='api.overseer'),
        ),
    ]
