# Generated by Django 5.2.7 on 2026-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventdiary_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseerexpensereport',
            name='expense_equipment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Equipment'),
        ),
        migrations.AddField(
            model_name='overseerexpensereport',
            name='expense_power',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Power'),
        ),
        migrations.AddField(
            model_name='overseerexpensereport',
            name='expense_sundries',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Sundries'),
        ),
        migrations.AddField(
            model_name='overseerexpensereport',
            name='expense_wine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Expense Wine'),
        ),
    ]
