# Generated by Django 5.2.7 on 2026-04-16 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tactsobranch_assigned_district_tactsobranch_overseer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffMember',
            new_name='AdminStaffMember',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='overseer',
        ),
        migrations.CreateModel(
            name='OverseerCommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('portfolio', models.CharField(max_length=255, verbose_name='Portfolio')),
                ('face_url', models.TextField(blank=True, verbose_name='Face URL')),
                ('added_at', models.TextField(blank=True, verbose_name='Added At')),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='api.overseer')),
            ],
        ),
        migrations.CreateModel(
            name='TactsoCommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('portfolio', models.CharField(max_length=255, verbose_name='Portfolio')),
                ('accepted_ts_and_cs', models.BooleanField(default=False)),
                ('face_url', models.TextField(blank=True, verbose_name='Face URL')),
                ('added_at', models.TextField(blank=True, verbose_name='Added At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_committee_members', to='api.tactsobranch')),
            ],
        ),
        migrations.DeleteModel(
            name='BranchCommitteeMember',
        ),
        migrations.DeleteModel(
            name='CommitteeMember',
        ),
    ]
