# Generated by Django 5.2.7 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_staffmember_adminstaffmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseer',
            name='chairperson_face_url',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='chairperson_name',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='secretary_face_url',
        ),
        migrations.RemoveField(
            model_name='overseer',
            name='secretary_name',
        ),
        migrations.AlterField(
            model_name='overseercommitteemember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
    ]
