# Generated by Django 5.2.7 on 2026-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_overseerexpensereport_expense_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseercommitteemember',
            name='signature_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Signature Data'),
        ),
    ]
