# Generated by Django 6.0.2 on 2026-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_overseercommitteemember_signature_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactsocommitteemember',
            name='added_at',
            field=models.TextField(auto_created=True, blank=True, verbose_name='Added At'),
        ),
    ]
