# Generated by Django 6.0.2 on 2026-06-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tactsocommitteemember_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaffmember',
            name='face_encorded_json',
            field=models.TextField(blank=True, default='[]', verbose_name='Face Encoded JSON'),
        ),
        migrations.AddField(
            model_name='overseercommitteemember',
            name='face_encorded_json',
            field=models.TextField(blank=True, default='[]', verbose_name='Face Encoded JSON'),
        ),
        migrations.AddField(
            model_name='tactsocommitteemember',
            name='face_encorded_json',
            field=models.TextField(blank=True, default='[]', verbose_name='Face Encoded JSON'),
        ),
    ]
