# Generated by Django 5.2.7 on 2026-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_visitor_remove_users_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='district_elder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='overseer_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
