# Generated by Django 6.0.2 on 2026-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_adminstaffmember_face_encorded_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('6th+ Year', '6th+ Year'), ('Postgraduate', 'Postgraduate'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Year of Study'),
        ),
    ]
