# Generated by Django 5.2.7 on 2026-04-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visitor_district_elder_name_visitor_overseer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseercommitteemember',
            name='accepted_ts_and_cs',
            field=models.BooleanField(default=False),
        ),
    ]
