# Generated by Django 6.0.2 on 2026-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_users_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseercommitteemember',
            name='church_office',
            field=models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother', 'Mother'), ('Father', 'Father')], max_length=50, null=True),
        ),
    ]
