# Generated by Django 6.0.2 on 2026-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_overseercommitteemember_church_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overseercommitteemember',
            name='church_office',
            field=models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother Deacon', 'Mother Deacon'), ('Mother Priest', 'Mother Priest'), ('Mother Community Elder', 'Mother Community Elder'), ('Father Deacon', 'Father Deacon'), ('Father Priest', 'Father Priest'), ('Father Community Elder', 'Father Community Elder'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
