# Generated by Django 5.2.7 on 2026-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_overseercommitteemember_accepted_ts_and_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_category',
            field=models.CharField(default='Testify', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
