# Generated by Django 5.2.7 on 2026-04-21 15:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_visitor_visitor_category_visitor_visitor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community_name', models.CharField(db_index=True, max_length=255)),
                ('member_uid', models.CharField(db_index=True, max_length=255)),
                ('is_visitor', models.BooleanField(default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('member_uid', 'date')},
            },
        ),
    ]
