# Generated by Django 6.0.2 on 2026-07-17 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_overseercommitteemember_church_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseerCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message_body', models.TextField(verbose_name='Message Body')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='api.overseer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverseerDiaryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('poster_url', models.TextField(blank=True, verbose_name='Poster URL')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Created By (UID or Name)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_events', to='api.overseer')),
            ],
        ),
        migrations.CreateModel(
            name='OverseerMeetingMinutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Meeting Title')),
                ('meeting_date', models.DateField(verbose_name='Meeting Date')),
                ('minutes_text', models.TextField(verbose_name='Minutes Details')),
                ('present_members', models.JSONField(blank=True, default=list, verbose_name='Present Members (JSON)')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='api.overseer')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_uid', on_delete=django.db.models.deletion.CASCADE, to='api.users', to_field='uid')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='api.overseercommunication')),
            ],
            options={
                'unique_together': {('communication', 'user')},
            },
        ),
    ]
