# Generated by Django 5.2.7 on 2026-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ready_for_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_category',
            field=models.CharField(default='Testify', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
