# Generated by Django 6.0.2 on 2026-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_overseercommunication_overseerdiaryevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseercommunication',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Attachment URLs (JSON)'),
        ),
    ]
