# Generated by Django 5.2.7 on 2026-04-23 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_visitor_ready_for_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('day', models.CharField(max_length=255, verbose_name='Day (e.g., 18 or 11 - 12)')),
                ('month', models.CharField(blank=True, max_length=255, verbose_name='Month (e.g., Apr)')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='EventContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Contributed')),
                ('has_contributed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contributions', to='api.overseer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='api.eventdiary')),
            ],
        ),
    ]
