# Generated by Django 6.0.2 on 2026-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_overseercommunication_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
