# Generated by Django 6.0.2 on 2026-08-16 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_visitor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TactsoMeetingMinutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Meeting Title')),
                ('meeting_date', models.DateField(verbose_name='Meeting Date')),
                ('minutes_text', models.TextField(verbose_name='Minutes Details')),
                ('present_members', models.JSONField(blank=True, default=list, verbose_name='Present Members (JSON)')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactso_meeting_minutes', to='api.tactsobranch')),
            ],
        ),
    ]
