# Generated by Django 5.2.7 on 2026-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_eventdiary_eventcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contract_signature_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='face_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='id_document_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_status',
            field=models.CharField(blank=True, default='Unverified', max_length=50, null=True),
        ),
    ]
