# Generated by Django 5.2.7 on 2026-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_users_contract_signature_url_users_face_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostolicGreeting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Greeting ID (Year)')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('apostle', models.CharField(max_length=255, verbose_name='Apostle Name')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('image_url', models.TextField(default='assets/profile_placeholder.png', verbose_name='Image URL')),
                ('content_json', models.JSONField(default=dict, verbose_name='Translations (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
