# Generated by Django 6.0.2 on 2026-08-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tactsomeetingminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='skills_services',
            field=models.JSONField(blank=True, default=list, verbose_name='Skills & Services'),
        ),
    ]
