# Generated by Django 5.2.7 on 2026-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_apostolicgreeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostolicgreeting',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apostolicgreeting',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
