# Generated by Django 6.0.2 on 2026-08-17 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_users_skills_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseermeetingminutes',
            name='google_meet_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Meet URL'),
        ),
        migrations.AddField(
            model_name='overseermeetingminutes',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Meeting Time'),
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.overseercommitteemember')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.overseermeetingminutes')),
            ],
            options={
                'unique_together': {('meeting', 'committee_member')},
            },
        ),
    ]
