# Generated by Django 5.2.7 on 2026-05-18 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_apostolicgreeting_likes_apostolicgreeting_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaffmember',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Personal Email'),
        ),
        migrations.AddField(
            model_name='songs',
            name='artist_type',
            field=models.CharField(blank=True, choices=[('Overseer', 'Overseer Chairperson'), ('Tactso', 'Tactso Chairperson')], max_length=50, null=True, verbose_name='Artist Type'),
        ),
        migrations.AddField(
            model_name='songs',
            name='contract_signed',
            field=models.BooleanField(default=False, verbose_name='Contract Signed'),
        ),
        migrations.AddField(
            model_name='songs',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Is Visible'),
        ),
        migrations.AddField(
            model_name='songs',
            name='overseer_chairperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'portfolio__icontains': 'chairperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseer_signed_songs', to='api.overseercommitteemember'),
        ),
        migrations.AddField(
            model_name='songs',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='songs',
            name='tactso_chairperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'portfolio__icontains': 'chairperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tactso_signed_songs', to='api.tactsocommitteemember'),
        ),
    ]
