# Generated by Django 6.0.2 on 2026-08-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_overseermeetingminutes_google_meet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactsomeetingminutes',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Meeting Time'),
        ),
        migrations.AlterField(
            model_name='tactsomeetingminutes',
            name='minutes_text',
            field=models.TextField(blank=True, null=True, verbose_name='Minutes Details'),
        ),
    ]
