# Generated by Django 5.2.7 on 2026-05-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_adminstaffmember_personal_email_songs_artist_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstaffmember',
            name='uid',
            field=models.CharField(max_length=255, verbose_name='UID'),
        ),
    ]
