# Generated by Django 6.0.2 on 2026-08-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tactsomeetingminutes_meeting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactsocommitteemember',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone'),
        ),
    ]
