# Generated by Django 5.2.7 on 2026-05-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_adminstaffmember_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='overseer_chairperson',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='tactso_chairperson',
        ),
    ]
