# WARNING: Do NOT commit this file to public version control!

# Keystore passwords and alias details for your new upload key
storePassword=ICTPass2022@
keyPassword=ICTPass2022@
keyAlias=upload

# Path to the keystore file, relative to the project root.
storeFile=upload-keystore.jks