// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos; 
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzMdLodURTOxmnlje_6QD2KiFPYJYzOEo',
    appId: '1:219784074240:web:9040575870effc0307b4e5',
    messagingSenderId: '219784074240',
    projectId: 'tact-3c612',
    authDomain: 'tact-3c612.firebaseapp.com',
    storageBucket: 'tact-3c612.firebasestorage.app',
    measurementId: 'G-QG20Z9H0TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAigV-EJXPZq41U1-K6930yVIvuCv_P9o',
    appId: '1:219784074240:android:558671265ae7d1a407b4e5',
    messagingSenderId: '219784074240',
    projectId: 'tact-3c612',
    storageBucket: 'tact-3c612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVYdaX8NO9emgLdgCZSBaM8ohlIgfakoU',
    appId: '1:219784074240:ios:b3c847e0e7b1a87e07b4e5',
    messagingSenderId: '219784074240',
    projectId: 'tact-3c612',
    storageBucket: 'tact-3c612.firebasestorage.app',
    iosBundleId: 'com.example.ttact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVYdaX8NO9emgLdgCZSBaM8ohlIgfakoU',
    appId: '1:219784074240:ios:b3c847e0e7b1a87e07b4e5',
    messagingSenderId: '219784074240',
    projectId: 'tact-3c612',
    storageBucket: 'tact-3c612.firebasestorage.app',
    iosBundleId: 'com.example.ttact',
  );
}
